query GlobalSearch(
  $search: String
  $noAdatasets: Boolean!
  $noFiles: Boolean!
  $noFolders: Boolean!
  $pagination: OffsetPaginationInput
) {
  adatasets: adatasets(
    filters: { search: $search }
    pagination: $pagination
  ) @skip(if: $noAdatasets) {
    ...ListADataset
  }

  files: files(
    filters: { search: $search }
    pagination: $pagination
  ) @skip(if: $noFiles) {
    ...ListFile
  }

  folders: folders(
    filters: { search: $search }
    pagination: $pagination
  ) @skip(if: $noFolders){
    ...ListFolder
  }
}
