query GlobalSearch(
  $search: String
  $noArrayDatasets: Boolean!
  $noFiles: Boolean!
  $noFolders: Boolean!
  $pagination: OffsetPaginationInput
) {
  arrayDatasets: arrayDatasets(
    filters: { search: $search }
    pagination: $pagination
  ) @skip(if: $noArrayDatasets) {
    ...ListArrayDataset
  }

  files: files(
    filters: { search: $search }
    pagination: $pagination
  ) @skip(if: $noFiles) {
    ...ListFile
  }

  folders: folders(
    filters: { search: $search }
    pagination: $pagination
  ) @skip(if: $noFolders){
    ...ListFolder
  }
}
