

fragment Graph on Graph {
  id
  name
  description
  ageName
  entityCategories {
    ...ListEntityCategory
  }
  protocolEventCategories {
    ...ListProtocolEventCategory
  }
  naturalEventCategories {
    ...ListNaturalEventCategory
  }
  relationCategories {
    ...ListRelationCategory
  }
  measurementCategories {
    ...ListMeasurementCategory
  }
  structureRelationCategories {
    ...ListStructureRelationCategory
  }
  queries {
    ...ListGraphQuery
  }
  pinned
  image {
    ...MediaStore
  }
}

fragment ListGraph on Graph {
  id
  name
  description
  pinned
  image {
    ...MediaStore
  }
}
