mutation AssertEntityExists($input: AssertEntityExistsInput!) {
  assertEntityExists(input: $input) {
    assertion {
      ...Assertion
    }
    instance {
      ...Instance
    }
    drawings {
      ...NodeDrawing
    }
  }
}

mutation AttestEntity($id: String!) {
  attestEntity(input: { id: $id }) {
    assertion {
      ...Assertion
    }
    instance {
      ...Instance
    }
    drawings {
      ...NodeDrawing
    }
  }
}

mutation RetractEntity($id: ID!) {
  retractEntity(input: { id: $id }) {
    assertion {
      ...Assertion
    }
    instance {
      ...Instance
    }
  }
}
