mutation AssertEntityExists($input: AssertEntityExistsInput!) {
  assertEntityExists(input: $input) {
    assertion {
      ...Assertion
    }
    entity {
      ...Entity
    }
    drawings {
      ...NodeDrawing
    }
  }
}

mutation AttestEntity($id: String!) {
  attestEntity(input: { id: $id }) {
    assertion {
      ...Assertion
    }
    entity {
      ...Entity
    }
    drawings {
      ...NodeDrawing
    }
  }
}

mutation RetractEntity($id: GraphID!) {
  retractEntity(input: { id: $id }) {
    assertion {
      ...Assertion
    }
    entity {
      ...Entity
    }
  }
}
