mutation AssertNaturalEventExists($input: AssertNaturalEventExistsInput!) {
  assertNaturalEventExists(input: $input) {
    assertion {
      ...Assertion
    }
    naturalEvent {
      ...NaturalEvent
    }
    drawings {
      ...NodeDrawing
    }
  }
}

mutation RetractNaturalEvent($id: String!) {
  retractNaturalEvent(input: { id: $id }) {
    assertion {
      ...Assertion
    }
    naturalEvent {
      ...NaturalEvent
    }
  }
}

mutation AttestNaturalEvent($id: String!) {
  attestNaturalEvent(input: { id: $id }) {
    assertion {
      ...Assertion
    }
    naturalEvent {
      ...NaturalEvent
    }
    drawings {
      ...NodeDrawing
    }
  }
}
