mutation AssertProtocolEventExists($input: AssertProtocolEventExistsInput!) {
  assertProtocolEventExists(input: $input) {
    assertion {
      ...Assertion
    }
    protocolEvent {
      ...ProtocolEvent
    }
    drawings {
      ...NodeDrawing
    }
  }
}

mutation RetractProtocolEvent($id: String!) {
  retractProtocolEvent(input: { id: $id }) {
    assertion {
      ...Assertion
    }
    protocolEvent {
      ...ProtocolEvent
    }
  }
}

mutation AttestProtocolEvent($id: String!) {
  attestProtocolEvent(input: { id: $id }) {
    assertion {
      ...Assertion
    }
    protocolEvent {
      ...ProtocolEvent
    }
    drawings {
      ...NodeDrawing
    }
  }
}
