mutation AssertRelationExists($input: AssertRelationExistsInput!) {
  assertRelationExists(input: $input) {
    assertion {
      ...Assertion
    }
    relation {
      ...Relation
    }
    drawings {
      ...EdgeDrawing
    }
  }
}

mutation UpdateRelation($input: UpdateRelationInput!) {
  updateRelation(input: $input) {
    assertion {
      ...Assertion
    }
    relation {
      ...Relation
    }
    drawings {
      ...EdgeDrawing
    }
  }
}

mutation RetractRelation($id: GraphID!) {
  retractRelation(input: { id: $id }) {
    assertion {
      ...Assertion
    }
    relation {
      ...Relation
    }
  }
}
