mutation AssertRelationExists($input: AssertRelationExistsInput!) {
  assertRelationExists(input: $input) {
    assertion {
      ...Assertion
    }
    link {
      ...Link
    }
    drawings {
      ...EdgeDrawing
    }
  }
}

mutation UpdateRelation($input: UpdateRelationInput!) {
  updateRelation(input: $input) {
    assertion {
      ...Assertion
    }
    link {
      ...Link
    }
    drawings {
      ...EdgeDrawing
    }
  }
}

mutation RetractRelation($id: ID!) {
  retractRelation(input: { id: $id }) {
    assertion {
      ...Assertion
    }
    link {
      ...Link
    }
  }
}
