mutation AssertStructureExists($input: AssertStructureExistsInput!) {
  assertStructureExists(input: $input) {
    assertion {
      ...Assertion
    }
    structure {
      ...Structure
    }
  }
}

mutation EnsureStructure($input: EnsureStructureInput!) {
  ensureStructure(input: $input) {
    assertion {
      ...Assertion
    }
    structure {
      ...Structure
    }
  }
}

mutation RetractStructure($id: GraphID!) {
  retractStructure(input: { id: $id }) {
    assertion {
      ...Assertion
    }
    structure {
      ...Structure
    }
  }
}

mutation UpdateStructure($input: UpdateStructureInput!) {
  updateStructure(input: $input) {
    assertion {
      ...Assertion
    }
    structure {
      ...Structure
    }
  }
}

mutation LinkStructureToEntity($input: LinkStructureInput!) {
  linkStructureToEntity(input: $input) {
    assertion {
      ...Assertion
    }
    structure {
      ...Structure
    }
  }
}
