query GetStructureKind($id: ID!) {
  structureKind(id: $id) {
    ...StructureKind
  }
}

query SearchStructureKinds($search: String, $values: [ID!]) {
  options: structureKinds(
    filters: { search: $search, ids: $values }
    pagination: { limit: 10 }
  ) {
    value: id
    label: identifier
  }
}

query ListStructureKinds(
  $filters: StructureKindFilter
  $pagination: VocabularyPaginationInput
) {
  structureKinds(filters: $filters, pagination: $pagination) {
    ...ListStructureKind
  }
}
