fragment BaseNode on Node {
  id
  label
  graph {
    id
  }
  label
}

fragment Node on Node {
  ...BaseNode
  ...Entity
  ...Structure
  ...Metric
}

fragment DetailNode on Node {
  ...Node
  graph {
    id
    name
  }
}

fragment PathActivity on Activity {
  id
  label
}
fragment PathStructure on Structure {
  id
  label
  kind {
    id
    identifier
    label
  }
}


fragment PathNode on Node {
  id

  ...PathActivity
  ...PathStructure
  ...PathEntity
  ...PathNaturalEvent
  ...PathProtocolEvent
  ...PathMetric
}


fragment ListNode on Node {
  id
  label
}
