
      export interface PossibleTypesResultData {
        possibleTypes: {
          [key: string]: string[]
        }
      }
      const result: PossibleTypesResultData = {
  "possibleTypes": {
    "Accessor": [
      "ImageAccessor",
      "LabelAccessor"
    ],
    "CoordinateSystemOwner": [
      "ADataset",
      "DataArray",
      "Lens",
      "MeshCollection",
      "Scene",
      "TableDataset"
    ],
    "DatasetImageFile": [
      "Dataset",
      "File",
      "Image"
    ],
    "Layer": [
      "AnnotationLayer",
      "ImageLayer",
      "MeshLayer",
      "PointLayer",
      "TrackLayer"
    ],
    "LayerRenderNode": [
      "BlendNode",
      "ChannelSourceNode",
      "PhasorNode",
      "ProjectionNode"
    ],
    "OpticalElement": [
      "BeamSplitterElement",
      "CCDElement",
      "DetectorElement",
      "FilterElement",
      "LampElement",
      "LaserElement",
      "LensElement",
      "MirrorElement",
      "ObjectiveElement",
      "OtherElement",
      "OtherSourceElement",
      "PinholeElement",
      "SampleElement"
    ],
    "Render": [
      "Snapshot",
      "Video"
    ],
    "Transformation": [
      "AffineTransformation",
      "BijectionTransformation",
      "ByDimensionTransformation",
      "FieldTransformation",
      "IdentityTransformation",
      "MapAxisTransformation",
      "RotationTransformation",
      "ScaleTransformation",
      "SequenceTransformation",
      "TranslationTransformation",
      "UnmappableTransformation"
    ],
    "View": [
      "AcquisitionView",
      "AffineTransformationView",
      "ChannelView",
      "ContinousScanView",
      "DerivedView",
      "FileView",
      "HistogramView",
      "InstanceMaskView",
      "LabelView",
      "LightpathView",
      "MaskView",
      "OpticsView",
      "RGBView",
      "ROIView",
      "ReferenceView",
      "ScaleView",
      "TimepointView",
      "WellPositionView"
    ],
    "_Entity": [
      "ADataset",
      "AcquisitionView",
      "AffineTransformation",
      "AffineTransformationView",
      "Animation",
      "AnimationWaypoint",
      "Annotation",
      "AnnotationCollection",
      "AnnotationLayer",
      "Axis",
      "BigFileStore",
      "BijectionTransformation",
      "ByDimensionTransformation",
      "Camera",
      "ChannelLabel",
      "ChannelView",
      "Client",
      "ContinousScanView",
      "CoordinateAnchor",
      "CoordinateSystem",
      "DataArray",
      "Dataset",
      "DerivedView",
      "Era",
      "Experiment",
      "FieldTransformation",
      "File",
      "FileView",
      "HistogramView",
      "IdentityTransformation",
      "Image",
      "ImageAccessor",
      "ImageLayer",
      "InstanceMaskView",
      "Instrument",
      "LabelAccessor",
      "LabelView",
      "Lens",
      "LightPath",
      "LightpathView",
      "MapAxisTransformation",
      "MaskView",
      "MediaStore",
      "Membership",
      "MeshCollection",
      "MeshLayer",
      "MultiWellPlate",
      "Objective",
      "OpticsView",
      "OptikitState",
      "Organization",
      "ParquetStore",
      "PhasorCalibration",
      "PhasorHistogram",
      "PointLayer",
      "RGBContext",
      "RGBView",
      "ROI",
      "ROIView",
      "ReferenceView",
      "RenderTree",
      "RotationTransformation",
      "ScaleTransformation",
      "ScaleView",
      "Scene",
      "SceneSnapshot",
      "SequenceTransformation",
      "Snapshot",
      "Stage",
      "Table",
      "TableDataset",
      "TableDatasetColumn",
      "Task",
      "TimepointView",
      "TrackLayer",
      "TranslationTransformation",
      "UnmappableTransformation",
      "User",
      "ValueHistogram",
      "Video",
      "ViewCollection",
      "WellPositionView",
      "ZarrStore"
    ]
  }
};
      export default result;
    