fragment ListMaterializedStructureRelationEdge on MaterializedStructureRelationEdge {
  id
  graph {
    id
    name
  }
  source {
    id
    identifier
  }
  target {
    id
    label
    identifier
  }
  edge {
    label
    id
    key
    term {
      ...ListTerm
    }
  }
}


fragment MaterializedStructureRelationEdge on MaterializedStructureRelationEdge {
  id
  graph {
    id
    name
  }
  source {
    id
    identifier
  }
  target {
    id
    label
    identifier
  }
  edge {
    label
    id
    key
    term {
      ...ListTerm
    }
  }
}
