query GetStructure($id: ID!) {
  structure(id: $id) {
    ...Structure
  }
}

query SearchStructures($id: ID, $search: String, $values: [ID!]) {
  options: structures(
    structureKindId: $id
    filters: { search: $search, ids: $values }
    pagination: { limit: 10 }
  ) {
    value: id
    label: object
  }
}

query GetInformedStructure(
  $identifier: StructureIdentifier!
  $object: StructureObject!
) {
  structureByIdentifier(identifier: $identifier, object: $object) {
    ...InformedStructure
  }
}

query ListStructures(
  $id: ID
  $filters: StructureFilter
  $pagination: StructurePaginationInput
  $ordering: [StructureOrder!]
) {
  structures(structureKindId: $id, filters: $filters, pagination: $pagination, ordering: $ordering) {
    ...ListStructure
  }
}

query InformingStructures($entityId: String!) {
  informingStructures(entityId: $entityId) {
    ...ListStructure
  }
}

query MetricsForStructure($structureId: ID!) {
  metricsForStructure(structureId: $structureId) {
    ...ListMetric
  }
}

query MetricsForAssertion($assertionId: ID!) {
  metricsForAssertion(assertionId: $assertionId) {
    ...ListMetric
  }
}
