name: Container Build

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jhnnsrs/orkestrator:latest
      - name: Refresh Go-Arkitekt-live
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GO_LIVE_HOST }}
          key: ${{ secrets.GO_LIVE_SSH_KEY }}
          username: ${{ secrets.GO_LIVE_USERNAME }}
          script: |
            cd /home/app
            docker compose pull
            docker compose up -d
