name: Release

on:
  push:
    branches: [main, dev]

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    outputs:
      new-release-published: ${{ steps.semantic-release.outputs.new-release-published }}
      new-release-version: ${{ steps.semantic-release.outputs.new-release-version }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }         # semantic-release needs full history
      - uses: actions/setup-node@v4
        with: { node-version: '22' }
      - run: yarn install --frozen-lockfile
      - name: Run semantic-release
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: npx semantic-release

  trigger-publish:
    needs: semantic-release
    runs-on: ubuntu-latest
    if: needs.semantic-release.outputs.new-release-published == 'true'
    steps:
      - name: Trigger publishall workflow
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'publishall.yaml',
              ref: context.ref
            })
