name: Release and Publish

on:
  push:
    branches: [main, dev]
  workflow_dispatch: {}

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }}       # electron-builder reads GH_TOKEN

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }         # semantic-release needs full history
      - uses: actions/setup-node@v4
        with: { node-version: '22' }
      - run: yarn install --frozen-lockfile
      - name: Run semantic-release
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: npx semantic-release